replicaCount: 2
imagePullSecrets:
  - name: docker-creds
fullnameOverride: everstake-frontend
nameOverride: everstake-frontend
terminationGracePeriodSeconds: 60
strategyRollingUpdate:
  enabled: false
  maxSurge: 50%
  maxUnavailable: 50%
readinessProbe:
  enabled: true
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3
  probes:
    - path: /
      port: 8080
      scheme: HTTP
livenessProbe:
  enabled: false
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3
  probes:
    - path: /
      port: 8080
      scheme: HTTP
networkPolicy:
  enabled: true
  allowExternal: true
image:
  name: null
  pullPolicy: IfNotPresent
env:
  enabled: false
  envs:
    - name: test
      value: test-value
service:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: app
container:
  ports:
    - port: 8080
      protocol: TCP
      name: http
antiAffinity:
  namespaces:
    - dev
resources:
  enabled: false
  limits:
    cpu: "1"
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 256Mi
nodeSelector: {}
tolerations: []
lifecycle: {}
